name: Build & Test

on: [push]

jobs:
  spm:
    name: SwiftPM build and test
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: Build swift packages
      run: swift build -v
    - name: Run tests
      run: swift test -v
  carthage:
    name: Xcode project build and test
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: Build xcode project
      run: xcodebuild build -scheme 'SubprocessMocks' -derivedDataPath .build
    - name: Run tests
      run: xcodebuild test -scheme 'Subprocess' -derivedDataPath .build
  cocoapods:
    name: Pod lib lint
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: Lib lint
      run: pod lib lint --verbose Subprocess.podspec
